FROM openjdk:11-jre

ARG API_USERNAME=****
ARG API_PASSWORD=****
ARG TWITTER_CONSUMER_KEY=****
ARG TWITTER_CONSUMER_SECRET=****
ARG TWITTER_ACCESS_TOKEN=****
ARG TWITTER_ACCESS_TOKEN_SECRET=****

COPY target/*.jar /opt/webapp.jar

CMD java -Dserver.port=$PORT $JAVA_OPTS -jar /opt/webapp.jar